# Generated by Django 4.1.1 on 2022-09-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_main',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
