# Generated by Django 4.1.1 on 2022-09-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_site', '0003_alter_article_image_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_src',
            field=models.FileField(upload_to=''),
        ),
    ]
